export const UPDATE_LOAN_AMOUNT = "UPDATE_LOAN_AMOUNT";
export const UPDATE_INTEREST_RATE = "UPDATE_INTEREST_RATE";
export const UPDATE_LOAN_TENURE = "UPDATE_LOAN_TENURE";
export const UPDATE_LOAN_START_PERIOD = "UPDATE_LOAN_START_PERIOD";
export const RESET_LOAN_DETAILS = "RESET_LOAN_DETAILS";
export const UPDATE_LOAN_PAYMENT_DETAILS = "UPDATE_LOAN_PAYMENT_DETAILS";
export const UPDATE_LOAN_PAYMENT_YEAR = "UPDATE_LOAN_PAYMENT_YEAR";
export const UPDATE_LOAN_PRE_PAYMENT_OPTIONS = "UPDATE_LOAN_PRE_PAYMENT_OPTIONS";
export const REMOVE_PRE_PAYMENT_OPTION = "REMOVE_PRE_PAYMENT_OPTION";

export const PRE_PAYMENT_TYPES = {
  PAY_PRINCIPAL_AMOUNT: "PAY_PRINCIPAL_AMOUNT",
  INCREASE_MONTHLY_EMI: "INCREASE_MONTHLY_EMI",
};
