export const UPDATE_LOAN_DETAILS = "UPDATE_LOAN_DETAILS";
export const RESET_LOAN_DETAILS = "RESET_LOAN_DETAILS";

export const UPDATE_LOAN_PAYMENT_DETAILS = "UPDATE_LOAN_PAYMENT_DETAILS";
export const UPDATE_LOAN_PAYMENT_YEAR = "UPDATE_LOAN_PAYMENT_YEAR";
export const UPDATE_LOAN_PRE_PAYMENT_OPTIONS =
  "UPDATE_LOAN_PRE_PAYMENT_OPTIONS";
export const REMOVE_PRE_PAYMENT_OPTION = "REMOVE_PRE_PAYMENT_OPTION";

export const PRE_PAYMENT_TYPES = {
  PAY_PRINCIPAL_AMOUNT: "PAY_PRINCIPAL_AMOUNT",
  INCREASE_MONTHLY_EMI: "INCREASE_MONTHLY_EMI",
};
export const PRE_PAYMENT_INTEREST_DIFF_TYPES = {
  LESSER: "Lesser",
  GREATER: "Greater",
  NO_PROFIT: "No Profit",
};
export const PRE_PAYMENT_COMPLETION_PERIOD_DIFF_TYPES = {
  EARLIER: "Earlier",
  LATER: "Later",
  SAME_PERIOD: "Same Time Period",
};
